### ISSUE TITLE
Web-App: Library pages won't work with relative urls

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#1060]
**Description**

WIth the current implementation library pages won't be able to render from relative urls, since we need to append the library carbon.yaml's location to the relative path, since per our docs, the path is relative to the carbon.yml

**Steps to reproduce**

We don't have a working example of this. you can reproduce with a mock library that uses a relative path for a navData:
```
# yaml-language-server: $schema=https://gist.githubusercontent.com/mattrosno/82ab63d4c2a709b3878a73b1f977a760/raw/202e9a0550bca3d08e3db9fb07097c14896915c6/carbon-resources.schema.json
library:
  id: overview-path-library
  name: Overview Path Library
  description: React implementation of Carbon Components
  navData:
  - title: A page
    path: './overview.mdx'
assets:
  accordion:
    name: Accordion
    description:
      An accordion is a vertically stacked list of headers that reveal or hide associated sections
      of content.
    status: stable
    type: component
    tags:
      - content-element
      - data-display
    framework: react
    platform: web
    docs:
      overviewPath: './overview.mdx'
```
