### ISSUE TITLE
Schema inheritance optimizations

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#126]
As an extension of https://github.com/carbon-design-system/carbon-platform/issues/7, there are a few things that we should consider when putting together the final version of our library and asset schema. Currently, it's structured like this:

```yml
id: accordion
inherits:
  asset: 'carbon-styles@latest/accordion'
  properties:
    - name
    - description
    - thumbnailPath
    - type
    - platform
status: stable
framework: react
```

## Auto detection

Can we crawl the package.json's to determine when inheritance is happening so it doesn't have to be explicitly stated? As package.json dependencies are just on the "library" level, this might not be possible because then how do we map assets within each library? It may be too restrictive for asset ids to match, or if asset names need to match if we slugify those. Also, there's no deterministic way to match assets by path as directory and file names may be different per language conventions.

On a similar note, can we auto-detect version based on package.json? That seems much more attainable.

## "Inheritable" properties

Do we want to specify which properties will automatically be inherited? This could make the config files smaller with less for maintainers to specify. For example, status should never be inherited, but properties like name, description, docs should be (if the inheriting asset doesn't specify those properties thus increasing specificity.)

## Exclusion instead of inclusion

With the current approach, if we add a new schema key, all metadata files would have to be updated to inherit the new key. Instead, if it was more of an exclusion model where we assume all inheritable properties will be inherited by default, that would be more future proof.
