### ISSUE TITLE
Determine page tabs per asset

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#485]
Most all Carbon components are documented using page tabs for Usage, Style, Code, and Accessibility content. For example, the [Accordion](https://www.carbondesignsystem.com/components/accordion/usage). We are continuing to use sub pages for asset documentation given the length and maturity of existing content. This issue is to determine the naming of the page tabs going forward.

Another thing to keep in mind is our markdown templates for [components with one or many variants](https://www.carbondesignsystem.com/contributing/component/#template-for-components-with-one-variant) and [patterns with one or many variants](https://www.carbondesignsystem.com/contributing/pattern/#how-to-write-a-pattern).

Proposals in comments below.

**To do**

- [x] Mock up proposal 2 and 3 and make decision this week so we can make schema changes next sprint @kingtraceyj

**Comment by mattrosno** [comment]
# Proposal 1

We simplify the page tabs to Overview, Design, Code and Accessibility.

### Overview

- What is it?
- When to use, when not to use it?
- What are related assets?
- Who maintains/contributes to it?

### Design

- How should the asset behave?
- What is the design spec?

### Code

- How to use the coded implementation?
- Where can I find additional API documentation?

### Accessibility

- What does provide?
- Design recommendations?
- Development considerations?

**Comment by mattrosno** [comment]
Answering your questions @ljcarot:

>Is there a reason you are changing the tab labels?

Yes. Each page tab will need an entry in the schema. The schema is our opportunity to define what information lives where.

```yml
assets:
  accordion:
    name: Accordion
    status: stable
    thumbnailPath: /docs/accordion.svg
    overviewPath: /docs/overview.mdx
    designPath: /docs/design.mdx
    codePath: /docs/code.mdx
    accessibilityPath: /docs/accessibility.mdx
```

>Is a change needed before release 1.0?

Yes. Or else we won't know where to get that content per asset.

>Will changing the labels slow down the migration of content from CDS to Platform?

No. It's not the end of the world if some content is in the wrong tab during initial migration. That can get cleaned up over time.
