### ISSUE TITLE
Add nav data to library schema

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#555]
Libraries need documentation pages that vary on a per-library basis. For example, some libraries have contribution guidance and Medium articles to highlight; other libraries have tutorials. This needs to happen through remote MDX pages, and the schema is how we can let the web application know what pages to link where in the side nav.

(1) In the shared schemas portion, create a `navData` entry: https://github.com/carbon-design-system/carbon-platform/blob/main/docs/resource-schemas.md#shared-schemas.

(2) The `navData` array should support two levels of navigation like:

```yml
navData:
  - title: A page
    path: '/a-page'
  - title: Another page
    items:
      - title: Sub page
        path: '/another-page/sub-page'
        hidden: true
      - title: Another sub page
        path: '/another-page/another-sub-page'
```

The `navData` array determines what MDX pages get rendered in the web app, as well as the link order in the side nav.

There's also a need for libraries to publish pages often in draft form that need to be live on the site but not linked to from the side nav. We could use a `hidden` key for that?

(3) Add `navData` as a library key and create a new version of the `@carbon-platform/schema` package.
