### ISSUE TITLE
Determine where Carbon patterns should live

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#714]
Carbon's website has 14 patterns: https://carbondesignsystem.com/patterns/overview. The Pattern and Asset Libraries (PALs) have additional portfolio and product-specific patterns that have been created and documented.

Carbon Next (https://next.carbondesignsystem.com/assets/patterns) has a patterns catalog where you can filter indexed patterns by sponsor, status, framework, and platform.

**License**

All of Carbon's 14 patterns are open source.

**Design kits**

One of the patterns has a Sketch design kit (text toolbar).

**Page tabs**

Per this issue (https://github.com/carbon-design-system/carbon-platform/issues/485#issuecomment-1101656076), if the pattern doesn't have code, style, or accessibility guidance, each pattern would have two page tabs.

1. Overview (the standardized dashboard and content)
2. Usage (existing content gets migrated here)

**Schema**

Per the schema (https://github.com/carbon-design-system/carbon-platform/blob/main/docs/resource-schemas.md), patterns are assets, and all assets need to belong to a library.

Versioning isn't incredibly important to design-only patterns, but having patterns live in libraries provides growth potential so a pattern could get a coded implementation, etc.

**Coded patterns**

This doesn't happen often, but Carbon Angular is an example of where there are coded examples of the loading, dialogs, filtering, and forms patterns documented in the Carbon website: https://angular.carbondesignsystem.com/?path=/story/patterns-loading--large-loading.

**Comment by mattrosno** [comment]
# Proposal B

Create a new library called `Carbon Patterns` that lives at a new folder: https://github.com/carbon-design-system/carbon/tree/main/packages.

No need to publish that as a package to NPM.

All indexing would be the same as proposal A.

A benefit to this is that the breadcrumb and pattern detail page would both say `Carbon Patterns` instead of `Carbon Core` as recommended above.

I see a few negatives to this approach.

1. The Carbon Angular library has patterns that we need to index. It already inherits Carbon Styles (https://github.com/IBM/carbon-components-angular/blob/master/src/carbon.yml#L7). We'd either need to add functionality so a library could inherit multiple libraries (which is messy), or add inheritance overrides so even if the library inherits library A, assets in that library could instead inherit an asset from library B (also messy).
2. It's hard to know what happens in the future, but if we end up shipping pattern-specific styling (Sass), it'd sure be nice for the pattern to live in the `Carbon Core` library (https://github.com/carbon-design-system/carbon/tree/main/packages/styles) to take advantage of that existing Sass build and publishing.

## Recommendation

Don't pursue this proposal.

**Comment by kingtraceyj** [comment]
@mattrosno I can see why you’re leaning towards proposal A. There are a few things that I am trying to wrap my head around with this one though.

The first is that is seems a little disjointed to have all other assets living together except patterns. As a designer, I would expect to find those things together. And styles and patterns feel like different types of things to me. Patterns more closely align with components. 

Secondly, as we think about indexing PALs, would they have the same issues potentially? I know that IBM products have a mix of coded and non-coded components (although they are all in react I think?) but we would also suggest proposal a to other teams with the same issue potentially? As a side note, some of IBM products patterns have style and code tabs in their PAL.

**Comment by mattrosno** [comment]
Libraries have assets; assets never live in isolation. Assets can be 1 of 4 types. That means that a library can have assets of type component and pattern, for example.

Libraries can inherit other libraries (where we match assets by `id` in inherited libraries.) The Carbon Styles library is used as the base library that Carbon React, Carbon Angular, etc. to inherit. This allows the framework collapsing in the catalogs:

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/1691245/168844644-c2864d16-31eb-4bb9-b136-0073723a0bb8.png">

It also allows one source of truth for content used by all libraries/assets that inherit it. The Carbon Styles library currently have these assets: https://web-app-prototype.j73b4w218e4.us-south.codeengine.appdomain.cloud/libraries/carbon-styles/latest/assets

Right now, the Carbon Styles library specifies content for asset:

* Name
* Description
* Thumbnail
* Type
* Platform
* Tags

With this, for example, Carbon React, Carbon Angular, Carbon Svelte, Carbon Vue, etc. don't have to specify those above properties. They are inherited from Carbon Styles.

But in the near future, additional content will be added to this library:

* Usage docs
* Style docs
* Accessibility docs

The Carbon Styles library is more than styles. But, when determining indexing strategy with the System Squad, we agree this to be the best candidate for the base library to use for inheritance. Because this library will contain more than styles, that's why proposal A recommends that we rename it to Carbon Core or Carbon Common.

> Patterns more closely align with components.

Proposal A does this. Components (the base component with no JavaScript implementation) live alongside our universal patterns (which also don't have coded implementation).

> Secondly, as we think about indexing PALs, would they have the same issues potentially? I know that IBM products have a mix of coded and non-coded patterns (although they are all in React I think?)

Proposal A can support this in a couple different scenarios.

1. An asset can be of type `pattern` and framework `react`, meaning the pattern has a coded implementation.
2. An asset can be of type `pattern` and framework `design-only`. That's the current state of our universal patterns. But also, the Carbon Angular library has coded implementations for four patterns. With our current inheritance model, we can state that the Angular-implemented pattern inherits the design-only pattern. Just like that screenshot above, in the patterns catalog, you'd be able to see that the pattern exists as design-only or Angular so you can filter and determine what you want to view. Because proposal A works for our universal patterns that are both design-only and coded, this model should work for PALs as well where there are coded and non-coded patterns.

> As a side note, some of IBM products patterns have style and code tabs in their PAL.

That's great. Per our asset detail page tabs, a pattern will by default only have Overview and Usage page tabs. As patterns are assets, and as assets can also have Style, Code, and Accessibility page tabs, we'll support patterns who have those additional page tabs.

**Comment by kingtraceyj** [comment]
Thanks for writing this all out. I think proposal A is making more sense after this explanation—and I agree, we would need to rename styles. 

A question about Libraries inheriting other libraries. I have where design kits live at the top of mind. If Carbon react inherits Carbon styles, does that mean that you could find the carbon pattern kits and the react components kit in the Carbon react library assets? I'm trying to understand how inherited assets would show up in the library asset pages and design kit pages.

**Comment by mattrosno** [comment]
@kingtraceyj good question. If you look at the proposed schema changes to add design kits, each library can specify a `designKits` array that is inheritable.

https://github.com/carbon-design-system/carbon-platform/blob/2415072d12b9df7d734777e26f017279f637d0bf/docs/resource-schemas.md#library-keys

That means the `carbon-styles` is indexed like:

```yml
library:
  id: carbon-styles
  name: Carbon Common
  description: Common components and patterns, as well as Sass styles when those assets have coded implementations.
  noIndex: true
  designKits:
    - carbon-white-sketch
    - carbon-g10-sketch
    - carbon-g90-sketch
    - carbon-g100-sketch
    - carbon-white-figma
    - carbon-g10-figma
    - carbon-g90-figma
    - carbon-g100-figma
    - carbon-white-adobe-xd
    - carbon-g10-adobe-xd
    - carbon-g90-adobe-xd
    - carbon-g100-adobe-xd
    - carbon-g10-axure
    - carbon-mid-fi-sketch
    - carbon-wireframe-invision-freehand
```

Then, Carbon React and the other libraries for Angular, Vue, etc. are indexed like:

```yml
library:
  id: carbon-react
  name: Carbon React
  description: React implementation of Carbon Components.
  inherits: carbon-styles
```

Since `designKits` gets inherited, then Carbon React, Carbon Angular, etc. have this after keys are inherited:

```yml
library:
  id: carbon-react
  name: Carbon React
  description: React implementation of Carbon Components.
  externalDocsUrl: https://react.carbondesignsystem.com
  inherits: carbon-styles
  designKits:
    - carbon-white-sketch
    - carbon-g10-sketch
    - carbon-g90-sketch
    - carbon-g100-sketch
    - carbon-white-figma
    - carbon-g10-figma
    - carbon-g90-figma
    - carbon-g100-figma
    - carbon-white-adobe-xd
    - carbon-g10-adobe-xd
    - carbon-g90-adobe-xd
    - carbon-g100-adobe-xd
    - carbon-g10-axure
    - carbon-mid-fi-sketch
    - carbon-wireframe-invision-freehand
```

And that's how the design kits page in each library would get populated. E.g., that list of above design kits would show up here for Carbon Components: https://web-app-prototype.j73b4w218e4.us-south.codeengine.appdomain.cloud/libraries/carbon-components/latest/design-kits

And Carbon React: https://web-app-prototype.j73b4w218e4.us-south.codeengine.appdomain.cloud/libraries/carbon-react/latest/design-kits

As well as Carbon Angular, Carbon Vue, etc.
