### ISSUE TITLE
Add asset page tabs to schema

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#792]
Similar to https://github.com/carbon-design-system/carbon-platform/issues/555 for libraries, each asset in the schema needs keys that determine which content is available to fetch and render as page tabs. It could possibly be a `docs` or `documentation` object that belongs to each `asset`. For example,

```yml
assets:
  accordion:
    name: Accordion
    documentation:
      usagePath: https://github.com/carbon-design-system/carbon-website/blob/main/src/pages/components/accordion/usage.mdx
      stylePath: /docs/style.mdx
      codePath: /docs/code.mdx
      accessibilityPath: /docs/accessibility.mdx
```

**Acceptance criteria**

- [x] Asset schema is updated to support documentation
- [x] The intent of each asset documentation page is specified in the schema

**Dependents**

There will be follow-on issues to wire up indexed documentation paths to page tabs, and to provide markdown templates for all four documentation pages.
