### ISSUE TITLE
Add usage, style, code, and accessibility documentation to assets in Carbon Styles library

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#890]
Add usage, style, code, and accessibility documentation to each component in Carbon styles

https://github.com/carbon-design-system/carbon/blob/main/packages/styles/carbon.yml

```
assets:
  accordion:
    name: Accordion
    description: An accordion is a vertically stacked list of headers that reveal or hide associated sections of content.
    externalDocsUrl: https://www.carbondesignsystem.com/components/accordion/usage
    status: stable
    type: component
    platform: web
    noIndex: true
    thumbnailPath: ./thumbnails/accordion.svg
    tags:
      - data-display
      - content-element
    docs:
      usagePath: https://github.com/carbon-design-system/carbon-website/blob/main/src/pages/components/accordion/usage.mdx
      stylePath: https://github.com/carbon-design-system/carbon-website/blob/main/src/pages/components/accordion/style.mdx
      codePath: https://github.com/carbon-design-system/carbon-website/blob/main/src/pages/components/accordion/code.mdx
      accessibilityPath: https://github.com/carbon-design-system/carbon-website/blob/main/src/pages/components/accordion/accessibility.mdx
```

Reference from carbon-website repo
https://github.com/carbon-design-system/carbon-website/tree/main/src/pages/components
